#!/bin/bash
# Execute Rapidumo tasks (every 3 days)

# import the global variable set.
. /var/archive-kit/rapidumo/cron/vars

# perform autoJanitor
$RAPIDUMO_PATH/cron/auto-janitor.sh

# sync Debian packages, if we are not in import freeze
if test "x$DEBIAN_SYNC_ENABLED" = xyes; then
  $RAPIDUMO_PATH/cron/sync-packages.sh
fi
