#!/bin/bash
# Execute daily Rapidumo tasks

# import the global variable set.
. /var/archive-kit/rapidumo/cron/vars

# sync the archive manipulation hints
$RAPIDUMO_PATH/cron/sync-hints.sh

# synchronize the Debian and Tanglu archives
$RAPIDUMO_PATH/cron/sync-packages.sh

# create new germinator output
$RAPIDUMO_PATH/cron/germinate-update.sh

# run Ben (the transition tracker)
$RAPIDUMO_PATH/cron/run-ben.sh

# perform autoJanitor
$RAPIDUMO_PATH/cron/auto-janitor.sh

# update the debcheck reports & pages
$RAPIDUMO_PATH/scripts/rapidumo --refresh-page debcheck

# now just update our static pages
$RAPIDUMO_PATH/scripts/rapidumo --refresh-page static
