---
General:
    distro_name: tanglu

MOM:
    path: /srv/patches.tanglu.org

Archive:
    path: /srv/archive.tanglu.org
    devel_suite: bartholomea
    staging_suite: staging
    export_dir: /srv/dak/export
    incoming: /pub/ftp/incoming

Synchrotron:
    sync_source:
        archs: amd64 armel armhf i386 ia64 mips mipsel powerpc s390 s390x sparc kfreebsd-amd64 kfreebsd-i386 m68k
    sync_enabled: false
    freeze_exceptions: /srv/dak/archive-hints/synchrotron/freeze-exceptions.txt

Janitor:
    hints_file: /srv/dak/archive-hints/britney/janitor

Templates:
    package_watch:

Suites:
    - name: aequorea
      components: main contrib non-free
      archs: amd64 i386

    - name: bartholomea
      components: main contrib non-free
      archs: amd64 i386

Fedmsg:
    prefix: "org.tanglu"
    sign: false
    environment: "dev"
    endpoints:
        "rapidumolib.curie":
            - "tcp://localhost:3000"
            - "tcp://localhost:3001"
            - "tcp://localhost:3002"
            - "tcp://localhost:3003"
