---
General:
    distro_name: tanglu
    html_output: /srv/dak/export/qa-pages
    britney_output_dir: /srv/qa.tanglu.org/staging-report/
    pkg_issues_dir: /srv/dak/export/pkg-issues/
    packages_mirror: /srv/archive.tanglu.org/

Archive:
    path: /srv/archive.tanglu.org
    build_queues_path: /srv/dak/queue/build
    devel_suite: dasyatis
    staging_suite: staging
    export_dir: /srv/dak/export
    incoming: /pub/ftp/incoming

Synchrotron:
    sync_source:
        suite: testing
        archs: amd64 armel armhf i386 ia64 mips mipsel powerpc s390 s390x sparc kfreebsd-amd64 kfreebsd-i386 m68k
    sync_enabled: true
    synchints_root: /srv/dak/archive-hints/synchrotron/
    debian_mirror: /srv/debian-src/

Janitor:
    hints_file: /srv/dak/archive-hints/britney/janitor

Suites:
    - name: staging
      components: main contrib non-free
      archs: amd64 i386
      incoming_queue: buildq-staging

    - name: aequorea
      components: main contrib non-free
      archs: amd64 i386

    - name: bartholomea
      components: main contrib non-free
      archs: amd64 i386

    - name: chromodoris
      components: main contrib non-free
      archs: amd64 i386

    - name: dasyatis
      components: main contrib non-free
      archs: amd64 i386

Fedmsg:
    prefix: "org.tanglu"
    sign: false
    environment: "dev"
    endpoints:
        "rapidumo.curie":
            - "tcp://localhost:3000"
            - "tcp://localhost:3001"
            - "tcp://localhost:3002"
            - "tcp://localhost:3003"
